theme = "gruvbox_dark_hard_akki"

[editor]
auto-pairs = false
line-number = "relative"
mouse = true
shell = ["zsh", "-c"]
cursorline = true
cursorcolumn = false
undercurl = true
bufferline = "always"
color-modes = true
true-color = true
completion-trigger-len = 1
rulers = [80, 120]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = true
follow-symlinks = true

[editor.indent-guides]
render = true
character = '|'
skip-levels = 1

[editor.lsp]
display-messages = true
display-inlay-hints = true
snippets = true

[editor.soft-wrap]
enable = true

[editor.whitespace.render]
newline = "all"

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = ["version-control"]
right = ["diagnostics", "selections", "position", "position-percentage", "file-encoding", "file-type", "file-line-ending"]

[keys.normal]
# esc = ['collapse_selection', 'keep_primary_selection']
H = "goto_first_nonwhitespace"
L = "goto_line_end"
A-l = "jump_view_right"
A-h = "jump_view_left"
A-j = "jump_view_down"
A-k = "jump_view_up"
tab = "goto_next_buffer"
S-tab = "goto_previous_buffer"

[keys.select]
H = "goto_first_nonwhitespace"
L = "goto_line_end"

# [keys.insert]
# esc = ["normal_mode", "move_char_left"]
